#!/usr/bin/env bash

set -e

PYTHON=".venv/Scripts/python.exe"

if [ ! -x "$PYTHON" ]; then
    echo "Virtual environment not found."
    exit 1
fi

python -m pytest . --doctest-modules
python -m pytest ./tests