#!/usr/bin/env bash

set -e

PYTHON=".venv/Scripts/python.exe"

if [ ! -x "$PYTHON" ]; then
    echo "Virtual environment not found."
    exit 1
fi

echo "Code Formatieren ..."
"$PYTHON" -m ruff check --fix --target-version=py314 .
"$PYTHON" -m ruff format --target-version=py314 .

echo "requirements.txt wird erstellt ..."
"$PYTHON" -m pip freeze > requirements.txt

git add -u
git add requirements.txt

echo "Hook erfolgreich."